Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -26,7 +26,7 @@ jobs:
         cmdline-tools-version: 'latest'
         packages: |
           cmdline-tools;latest
-
+          
     - name: Accept SDK licenses
       run: yes | sdkmanager --licenses || true
 
@@ -48,13 +48,24 @@ jobs:
     - name: Start Emulator
       run: |
         # Start the emulator in the background
-        nohup emulator -avd test -no-window -no-audio -no-boot-anim -accel off &
-  
+        emulator -avd test -no-window -no-audio -no-boot-anim -accel off &
+
         # Wait for the device to be ready
         adb wait-for-device
-  
-        # Wait until the emulator has fully booted
-        until adb shell getprop sys.boot_completed | grep -m 1 '1'; do
+
+        # Wait until the emulator has fully booted (Increase timeout if needed)
+        timeout=600 # 10 minutes timeout
+        start_time=$(date +%s)
+        while true; do
+          if adb shell getprop sys.boot_completed | grep -m 1 '1'; then
+            break
+          fi
+          current_time=$(date +%s)
+          elapsed_time=$(( current_time - start_time ))
+          if [ $elapsed_time -ge $timeout ]; then
+            echo "Emulator failed to boot within the expected time."
+            exit 1
+          fi
           sleep 1
         done
 
